services:
  hls-downloader:
    build: .
    container_name: hls-downloader-service
    restart: unless-stopped
    env_file:
      - .env
    environment:
      YT_DLP_PATH: /usr/local/bin/yt-dlp
    ports:
      - "3301:3000"
    volumes:
      - ./data:/app/data
      - ./downloads:/app/downloads
